name: Auto run and archive

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  auto:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Update chapters
        run: bash downloader.sh
      
      - name: Get current date
        if: ${{ steps.commit.outputs.alive != 'false' }}
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Upload
        if: ${{ steps.commit.outputs.alive != 'false' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: archive-${{ steps.date.outputs.date }}
          prerelease: false
